# Site settings
title: Malihini Orchid Society
email: Malihini.society@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The Malihini Orchid Society is a non-Profit  all-volunteer organization
  dedicated to the  appreciation, cultivation and conservation of Earth's
  orchid species and hybrids. Membership in Malihini is open to all members
  of our community.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://malihini.org" # the base hostname & protocol for your site
facebook_username: Malihini-Orchid-Society-1570771156515839
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
markdown: kramdown

future: true

#trying to add settings to remove the need for the yml header
defaults:
  -
    scope:
      path: news/_posts
    values:
      layout: "post"
  -
